---
version: '3'
services:
  web:
    build: .
    image: lab-flask-sqlalchemy
    ports:
      - 5000:5000
    environment:
      DATABASE_URI: "mysql+pymysql://dbuser:passw0rd@db:3306/petstore"
    networks:
      - overlay
    depends_on:
      - db

  db:
    image: mariadb:latest
    hostname: mysql
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: passw0rd
      MYSQL_DATABASE: petstore
    networks:
      - overlay

volumes:
  dbdata:

networks:
  overlay:
